# -*- coding: utf-8 -*-
"""export-control.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PaHZqLsDNArcczyxkWZZd-2_TW2plA13
"""

from bs4 import BeautifulSoup
import requests
import pandas as pd
import re

def get_raw_data():
    url = 'https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32021R0821'
    # Get HTTP request from this URL using the `requests`
    page = requests.get(url)

    # Read the text using the specified format
    soup = BeautifulSoup(page.text, 'html')

    annex1 = soup.find('div', id='L_2021206EN.01002501')
    annex1 = annex1.div

    part2 = annex1.find_all('p', id="L_2021206EN.01002501-g-012-0012")

    part2 = part2[0].find_next_siblings(any)
    part2 = [i.text.strip().replace('\n', " ").replace('\r', " ").replace('\t', " ").replace('\xa0', " ").replace('\'', " ").replace('\"', " ") for i in part2]
    part2 = str(part2).strip('[]')
    return part2